'use client';

import { useMemo, useState } from 'react';

type Tale = { id:string; title:string; punjabi:string; region:string; category:'Wisdom'|'Courage'|'Love'|'Wonder'|'Family'; summary:string; lesson:string; characters:string[]; shape:'river'|'lion'|'bird'|'tree'|'moon' };
const tales:Tale[]=[
{id:'sohni',title:'Sohni and the River',punjabi:'ਸੋਹਣੀ ਮਹੀਂਵਾਲ',region:'Chenab region',category:'Love',summary:'A tragic river legend remembered across Punjab through song, qissa poetry, painting, and oral storytelling.',lesson:'Love can be powerful, but choices made under pressure can carry irreversible consequences.',characters:['Sohni','Mahiwal'],shape:'river'},
{id:'sparrow',title:'The Clever Sparrow',punjabi:'ਚਤੁਰ ਚਿੜੀ',region:'Village Punjab',category:'Wisdom',summary:'A small bird survives danger by observing carefully, speaking at the right moment, and refusing to panic.',lesson:'Clear thinking can defeat strength when fear does not take control.',characters:['Sparrow','Farmer','Cat'],shape:'bird'},
{id:'lion',title:'The Lion and the Jackal',punjabi:'ਸ਼ੇਰ ਤੇ ਗਿੱਦੜ',region:'Malwa folk tradition',category:'Courage',summary:'A boastful jackal learns that borrowed power disappears when real danger arrives.',lesson:'Real courage is proven by action, not by loud claims.',characters:['Lion','Jackal'],shape:'lion'},
{id:'tree',title:'The Banyan Tree Promise',punjabi:'ਬੋਹੜ ਦਾ ਵਾਅਦਾ',region:'Doaba villages',category:'Family',summary:'Generations of one family return to the same tree, keeping a promise of care, memory, and responsibility.',lesson:'Families stay strong when promises are renewed through action.',characters:['Grandmother','Child','Village elders'],shape:'tree'},
{id:'moon',title:'The Weaver and the Moon',punjabi:'ਜੁਲਾਹਾ ਤੇ ਚੰਦ',region:'West Punjab oral tradition',category:'Wonder',summary:'A poor weaver follows moonlight across fields and discovers that imagination can lead to practical wisdom.',lesson:'Wonder is valuable when it helps us see ordinary life differently.',characters:['Weaver','Moon','Traveller'],shape:'moon'}];
const categories=['All','Wisdom','Courage','Love','Wonder','Family'] as const;

export default function FolkTalesMuseum(){
 const [category,setCategory]=useState<(typeof categories)[number]>('All'); const [selected,setSelected]=useState<Tale>(tales[0]);
 const visible=useMemo(()=>category==='All'?tales:tales.filter(t=>t.category===category),[category]);
 function chooseCategory(value:(typeof categories)[number]){setCategory(value);const first=value==='All'?tales[0]:tales.find(t=>t.category===value);if(first)setSelected(first)}
 return <main className="sv-page">
  <section className="border-b border-black/10 bg-[#5c3c74] text-white"><div className="sv-container grid gap-10 py-14 md:py-20 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#f2d59b]">Punjabi Folk Tales Museum</p><h1 className="mt-5 max-w-[12ch] font-serif text-5xl font-bold leading-[.97] tracking-[-.04em] md:text-7xl">Stories that travelled from courtyard to courtyard.</h1><p className="mt-6 max-w-2xl text-base font-medium leading-8 text-white/75">Explore folk legends, village tales, moral stories, and wonder-filled narratives from across Punjab.</p></div><TaleArt tale={selected} large/></div></section>
  <section className="sv-container py-8"><div className="flex gap-2 overflow-x-auto pb-2">{categories.map(v=><button key={v} onClick={()=>chooseCategory(v)} className={`min-w-max rounded-full px-5 py-3 text-sm font-black ${category===v?'bg-[#201712] text-white':'border border-black/10 bg-[#fffdf8]'}`}>{v}</button>)}</div></section>
  <section className="sv-container pb-16"><div className="grid gap-8 lg:grid-cols-[22rem_1fr]"><aside className="space-y-3 lg:sticky lg:top-6 lg:self-start">{visible.map(t=><button key={t.id} onClick={()=>setSelected(t)} className={`grid w-full grid-cols-[5rem_1fr] items-center gap-4 rounded-[1.5rem] border p-4 text-left transition ${selected.id===t.id?'border-[#5c3c74] bg-[#f5edf9] shadow-lg':'border-black/10 bg-[#fffdf8] hover:-translate-y-.5'}`}><TaleArt tale={t} compact/><div><p className="font-serif text-xl font-bold">{t.title}</p><p className="mt-1 font-black text-[#6f1d1b]">{t.punjabi}</p><p className="mt-2 text-xs font-black uppercase tracking-[.14em] text-[#6f675f]">{t.category}</p></div></button>)}</aside>
  <article className="overflow-hidden rounded-[2rem] border border-black/10 bg-[#fffdf8] shadow-[0_22px_60px_rgba(54,35,24,.1)]"><div className="grid gap-8 bg-[#eee4f2] p-7 md:grid-cols-[1fr_.72fr] md:items-center md:p-10"><div><p className="sv-kicker">{selected.region}</p><h2 className="mt-3 font-serif text-5xl font-bold tracking-[-.03em]">{selected.title}</h2><p className="mt-2 text-3xl font-black text-[#6f1d1b]">{selected.punjabi}</p><p className="mt-5 text-base font-medium leading-8 text-[#5f564d]">{selected.summary}</p></div><TaleArt tale={selected}/></div><div className="grid gap-8 p-7 md:p-10 lg:grid-cols-[1fr_18rem]"><section><p className="sv-kicker">Story lesson</p><p className="mt-5 text-xl font-medium leading-9 text-[#403830]">{selected.lesson}</p><div className="mt-8 border-t border-black/10 pt-8"><p className="sv-kicker">Main characters</p><div className="mt-4 flex flex-wrap gap-3">{selected.characters.map(c=><span key={c} className="rounded-full border border-black/10 bg-[#fff8e8] px-4 py-2 text-sm font-bold">{c}</span>)}</div></div></section><aside className="rounded-[1.5rem] bg-[#201712] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-[#e7b650]">Category</p><p className="mt-4 font-serif text-3xl font-bold">{selected.category}</p><p className="mt-6 text-sm leading-7 text-white/65">Built for future narration, classroom discussion, and family storytelling.</p></aside></div></article></div></section>
 </main>
}

function TaleArt({tale,compact=false,large=false}:{tale:Tale;compact?:boolean;large?:boolean}){const cls=compact?'h-20 w-20 rounded-2xl border border-black/10 bg-[#f5e7ca]':large?'w-full rounded-[2rem] border border-white/10 bg-[#f5e7ca] p-4 shadow-2xl':'w-full rounded-[1.5rem] border border-black/10 bg-[#f5e7ca] p-3';return <svg viewBox="0 0 420 320" role="img" aria-label={`${tale.title} illustration`} className={cls}><rect width="420" height="320" rx="24" fill="#f5e7ca"/><circle cx="340" cy="55" r="28" fill="#d99a22"/><path d="M0 275c100-42 210-42 315 0 45 18 77 18 105 5v40H0z" fill="#d8bd7b"/>{tale.shape==='river'&&<><path d="M0 225c120-45 245 35 420-10v105H0z" fill="#4f8ea8"/><path d="M125 218c35-70 135-70 170 0" fill="none" stroke="#6f1d1b" strokeWidth="15"/><circle cx="126" cy="190" r="18" fill="#c98a72"/><circle cx="294" cy="190" r="18" fill="#c98a72"/></>}{tale.shape==='bird'&&<><ellipse cx="210" cy="176" rx="70" ry="50" fill="#315a45"/><circle cx="258" cy="142" r="30" fill="#315a45"/><path d="m282 142 35 12-35 12z" fill="#d99a22"/><circle cx="267" cy="135" r="5" fill="#201712"/><path d="M150 166c-45-34-72-22-88 12" fill="none" stroke="#6f1d1b" strokeWidth="14"/></>}{tale.shape==='lion'&&<><circle cx="210" cy="150" r="72" fill="#b9782f"/><circle cx="210" cy="158" r="48" fill="#d9a35a"/><circle cx="191" cy="148" r="5" fill="#201712"/><circle cx="229" cy="148" r="5" fill="#201712"/><path d="M190 180c14 12 26 12 40 0" fill="none" stroke="#6f1d1b" strokeWidth="7"/><path d="M165 226h90" stroke="#8a5b1f" strokeWidth="18" strokeLinecap="round"/></>}{tale.shape==='tree'&&<><path d="M210 270V145" stroke="#8a5b1f" strokeWidth="30" strokeLinecap="round"/><circle cx="210" cy="110" r="75" fill="#315a45"/><circle cx="155" cy="145" r="48" fill="#48775d"/><circle cx="268" cy="145" r="48" fill="#48775d"/><circle cx="185" cy="95" r="10" fill="#d99a22"/><circle cx="240" cy="130" r="10" fill="#d99a22"/></>}{tale.shape==='moon'&&<><circle cx="210" cy="135" r="78" fill="#f1cf72"/><circle cx="242" cy="110" r="78" fill="#f5e7ca"/><path d="M100 255c38-65 182-65 220 0" fill="#5c3c74"/><path d="M192 240v-72M228 240v-72M192 168h36" stroke="#fff6df" strokeWidth="10" strokeLinecap="round"/></>}</svg>}
